# Generated by Django 6.0 on 2026-01-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('hospital', 'بیمارستانی'), ('city', 'شهری')], max_length=20)),
                ('work_time', models.CharField(choices=[('daily', 'روزانه'), ('24h', 'شبانه روزی')], max_length=20)),
                ('job_title', models.CharField(choices=[('investor', 'سرمایه\u200cگذار'), ('pharmacist_partner', 'داروساز مشارکت مدنی و همکاری'), ('pharmacist_responsible', 'داروساز مسئول فنی'), ('pharmacist_deputy', 'داروساز قائم مقام'), ('staff', 'پرسنل داروخانه'), ('technician', 'تکنسین دارویی'), ('cosmetics_seller', 'فروشنده آرایشی بهداشتی'), ('accountant', 'حسابدار'), ('intern', 'کارآموز'), ('other', 'سایر')], max_length=30)),
                ('cooperation_duration', models.CharField(choices=[('long', 'بلندمدت'), ('short', 'کوتاه\u200cمدت'), ('shift', 'شیفتی')], max_length=20)),
                ('experience', models.CharField(choices=[('none', 'الزامی نیست'), ('1-3', '۱-۳ سال'), ('3+', '۳ سال به بالا')], max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('any', 'فرقی ندارد')], default='any', max_length=10)),
                ('age_from', models.PositiveIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='app_accounts.userprofile')),
            ],
        ),
    ]
